name: Build TWRP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    # 1. Скрипт очистки сервера: удаляем лишний софт и освобождаем тонну места под память
    - name: Максимальное освобождение памяти сервера
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 24576
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: Подготовка сервера
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential tar zip curl git python3 wget

    - name: Сборка TWRP
      run: |
        git config --global user.email "bot@twrp.me"
        git config --global user.name "TWRP-Bot"
        export REPO_NOT_TERMINAL=1
        
        mkdir twrp && cd twrp
        
        # Скачиваем repo через wget
        wget -q https://githubusercontent.com -O ./repo
        chmod 777 ./repo
        chmod +x ./repo
        
        # Запускаем init и sync
        ./repo init -u https://github.com -b twrp-12.1 --no-clone-bundle --depth=1
        ./repo sync -j2 --force-sync --no-clone-bundle --no-tags -q
        
        # Скачиваем дерево устройства для Samsung Tab S7 FE 5G
        git clone -q https://github.com -b android-12.1 device/samsung/gts7xllite
        
        . build/envsetup.sh
        lunch twrp_gts7xllite-eng
        
        # Компилируем в 1 поток, имея гигантский запас виртуальной памяти в 24 ГБ
        mka recoveryimage -j1
