name: Build TWRP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Подготовка системы и памяти
      run: |
        # 1. Обновляем пакеты и ставим нужный софт
        sudo apt-get update
        sudo apt-get install -y bc build-essential tar zip curl git python3 wget
        
        # 2. Создаем файл подкачки на 10 ГБ чистыми командами Linux
        sudo swapoff -a
        sudo dd if=/dev/zero of=/swapfile bs=1M count=10240
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Сборка TWRP
      run: |
        git config --global user.email "bot@twrp.me"
        git config --global user.name "TWRP-Bot"
        export REPO_NOT_TERMINAL=1
        
        mkdir twrp && cd twrp
        
        # Скачиваем рабочий скрипт repo через wget
        wget -q https://githubusercontent.com -O ./repo
        chmod +x ./repo
        
        # Запускаем инициализацию и тихое скачивание
        ./repo init -u https://github.com -b twrp-12.1 --no-clone-bundle --depth=1
        ./repo sync -j2 --force-sync --no-clone-bundle --no-tags -q
        
        # Скачиваем дерево устройства для вашего Samsung Tab S7 FE 5G
        git clone -q https://github.com -b android-12.1 device/samsung/gts7xllite
        
        # Запуск компиляции в безопасном режиме (2 потока)
        . build/envsetup.sh
        lunch twrp_gts7xllite-eng
        mka recoveryimage -j2
