name: Build TWRP
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Ручное освобождение места и настройка памяти
      run: |
        # 1. Безопасно удаляем тяжелый встроенный Android SDK от GitHub, чтобы освободить 25 ГБ места
        sudo rm -rf /usr/local/lib/android
        
        # 2. Создаем гигантский файл подкачки на 16 ГБ стандартными командами Linux
        sudo swapoff -a
        sudo dd if=/dev/zero of=/swapfile bs=1M count=16384
        sudo chmod 600 /swapfile
        sudo mkswap /swapfile
        sudo swapon /swapfile

    - name: Подготовка зависимостей
      run: |
        sudo apt-get update
        sudo apt-get install -y bc build-essential tar zip curl git python3 wget

    - name: Сборка TWRP
      run: |
        git config --global user.email "bot@twrp.me"
        git config --global user.name "TWRP-Bot"
        export REPO_NOT_TERMINAL=1
        
        mkdir twrp && cd twrp
        
        # Скачиваем рабочий repo через wget
        wget -q https://githubusercontent.com -O ./repo
        chmod 777 ./repo
        chmod +x ./repo
        
        # Запускаем инициализацию и тихое скачивание
        ./repo init -u https://github.com -b twrp-12.1 --no-clone-bundle --depth=1
        ./repo sync -j2 --force-sync --no-clone-bundle --no-tags -q
        
        # Скачиваем дерево устройства для Samsung Tab S7 FE 5G
        git clone -q https://github.com -b android-12.1 device/samsung/gts7xllite
        
        # Компиляция
        . build/envsetup.sh
        lunch twrp_gts7xllite-eng
        mka recoveryimage -j1
